image: Visual Studio 2017
#skip_branch_with_pr: true
install:
    - sh: set_python_envs.sh
build: off
test_script:
    - sh: env PYTHON=$HOME/miniconda3/envs/intel3/bin/python ./run.sh --repeat 1 --size 16
deploy: off
