version: 1.0.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
shallow_clone: true
install:
- C:\msys64\bin\bash.exe set_python_envs.sh
build_script:
- C:\msys64\bin\bash.exe -c PYTHON=$HOME/miniconda3/envs/default3/bin/python ./run.sh --repeat 1 --size 512 --steps 2
- C:\msys64\bin\bash.exe -c PYTHON=$HOME/miniconda3/envs/pip3/bin/python ./run.sh --repeat 1 --size 512 --steps 2
deploy: off
